import Head from "next/head";
import type { NextPage } from "next";
import 'reactjs-popup/dist/index.css'
import Tags from "components/Tags";
import Carousel from "components/Carousel"
import Testomonials from "components/Testmonials";

import Image from "next/image";
import MyProjects from "components/MyProjects";
import { ImportContacts } from "@mui/icons-material";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="smooth-scroll min-h-screen bg-gradient-to-b from-[#c7a4c8] to-[#2c5da8]">
        <Tags />
        <div className="flex min-h-screen flex-col items-center justify-center">
          <h1 className="text-6xl text-white">Kevin Huang</h1>
          <h1 className="mt-4 text-3xl text-white">About me</h1>
          <Image
            src="/Kevinmemoji.png"
            alt="icon of me"
            width={150}
            height={50}
            className="m-5 rounded-[50%]"
          />
          <div className="mt-2 w-4/5 text-center text-lg text-white md:w-1/2 md:text-2xl">
            <h2>
              Hello! My name is Kevin Huang. I am currently in Year 11 with a
              incredible passion for Web Design and Software Development. I am
              hard working, dedicated, and highly passionate in the industry
              with a lot to learn.
            </h2>
          </div>
        </div>
      </main>
      {/* <Carousel /> */}
      <MyProjects />
      <Testomonials />
    </>
  );
};

export default Home;


// 