import Head from "next/head";
import type { NextPage } from "next";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";
import Projects from "../../components/Projects"

import { api } from "~/utils/api";
import Image from "next/image";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#4ea3aa] to-[#3270ce]">
        <h1 className="text-5xl text-white">Kevin Huang</h1>
        <h1 className="mt-4 text-3xl text-white">About me</h1>
        <Image
          src="/Kevinmemoji.png"
          alt="icon of me"
          width={150}
          height={50}
          className="m-5 rounded-[50%]"
        />
        <div className="mt-2 w-1/2 text-center text-white">
          <h2>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim
            ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
            aliquip ex ea commodo consequat. Duis aute irure dolor in
            reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
            culpa qui officia deserunt mollit anim id est laborum.
          </h2>
        </div>
      </main>
      <h1 className="text-5xl text-center align-middle mt-10">My Projects</h1>
      <div className="flex justify-center min-h-screen">
        <Projects projectName="Frame Website" projectGitURL="" projectImage=""/>
        <Projects projectName="Report Generator" projectGitURL="" projectImage=""/>
        <Projects projectName="Anime Recomendation" projectGitURL="" projectImage=""/>
        <Projects projectName="Login App" projectGitURL="" projectImage=""/>
      </div>
    </>
  );
};

export default Home;


// min-h-screen bg-[url('../../public/background.jpg')] bg-cover bg-fixed