import Head from "next/head";
import type { NextPage } from "next";
import 'reactjs-popup/dist/index.css'
import Tags from "components/Tags";
import Testomonials from "components/Testmonials";

import Image from "next/image";
import MyProjects from "components/MyProjects";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="smooth-scroll min-h-screen bg-[#AEC6CF]">
        <Tags />

        <div className="flex min-h-screen flex-col items-center justify-center">
          <div className={"m-0 text-center place-content-center grid min-h-full"}>
            <h1 className={"font-sdf relative text-gray-700 before:content-[''] before:absolute before:top-0 before:right-0 before:left-0 before:bottom-0 after:absolute after:top-0 after:right-0 after:left-0 after:bottom-0 before:bg-[#AEC6CF] before:animate-typewriter after:w-[.125em] after:bg-black after:animate-blink after:animate-typewriter"} style={{
              fontSize: "clamp(1rem, 3vw + 1rem, 4rem)"

            }}>Hello, my name is Kevin</h1>
          </div>
          <div className="text-gray-600 font-sourcecode text-xl text-bold text-center">I am a High School Student at Cherrybrook Technology High School. </div>
          {/*<h1 className="text-6xl text-white">Kevin Huang</h1>*/}
          {/*<h1 className="mt-4 text-3xl text-white">About me</h1>*/}
          {/*<Image*/}
          {/*  src="/Kevinmemoji.png"*/}
          {/*  alt="icon of me"*/}
          {/*  width={150}*/}
          {/*  height={50}*/}
          {/*  className="m-5 rounded-[50%]"*/}
          {/*/>*/}
          {/*<div className="mt-2 w-4/5 text-center text-lg text-white md:w-1/2 md:text-2xl">*/}
          {/*  <h2>*/}
          {/*    Hello! My name is Kevin Huang. I am currently in Year 11 with a*/}
          {/*    incredible passion for Web Design and Software Development. I am*/}
          {/*    hard working, dedicated, and highly passionate in the industry*/}
          {/*    with a lot to learn.*/}
          {/*  </h2>*/}
          {/*</div>*/}
        </div>
      </main>
      {/* <Carousel /> */}
      <MyProjects />
      <Testomonials />
    </>
  );
};

export default Home;


// 